import jsPDF from "jspdf";
import type { CalcResult } from "./tax/engine";

/* ASCII-safe currency formatter for jsPDF (no locale unicode chars) */
const pdfMoney = (n: number) => {
  const abs = Math.abs(n);
  const formatted = abs.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `GBP ${formatted}`;
};

export function downloadPayslipPdf(result: CalcResult, opts: { region: string; pensionPct: number; studentLoan: string }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = 595;
  let y = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("UK Net Pay - Annual Statement", 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  y += 18;
  doc.text(`Tax year 2026/27 | Region: ${opts.region} | Pension: ${opts.pensionPct}% | Student loan: ${opts.studentLoan}`, 40, y);
  y += 30;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 20;

  const row = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(11);
    doc.setTextColor(bold ? 0 : 60);
    doc.text(label, 40, y);
    doc.text(value, W - 40, y, { align: "right" });
    y += 18;
  };

  row("Gross salary", pdfMoney(result.totalGross));
  row("Pension contribution", `-${pdfMoney(result.pension)}`);
  row("Taxable gross", pdfMoney(result.taxableGross));
  row("Personal allowance", pdfMoney(result.personalAllowance));
  row("Taxable income", pdfMoney(result.taxableIncome));
  y += 4;
  row("Income Tax", `-${pdfMoney(result.incomeTax)}`);
  row("National Insurance", `-${pdfMoney(result.ni)}`);
  if (result.studentLoan > 0) row("Student Loan", `-${pdfMoney(result.studentLoan)}`);
  y += 10;
  doc.line(40, y, W - 40, y);
  y += 18;
  row("Net take-home (annual)", pdfMoney(result.net), true);
  row("Net take-home (monthly)", pdfMoney(result.net / 12), true);
  row("Effective rate", `${result.effectiveRate.toFixed(2)}%`, true);

  y += 30;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by uknetpay.co.uk | For information only | Not financial advice.", 40, y);

  doc.save(`uknetpay-${Math.round(result.totalGross)}.pdf`);
}