import jsPDF from "jspdf";
import type { CalcResult } from "./tax/engine";
import { fmt2 } from "./format";

export function downloadPayslipPdf(result: CalcResult, opts: { region: string; pensionPct: number; studentLoan: string }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = 595;
  let y = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("UK Net Pay — Annual Statement", 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  y += 18;
  doc.text(`Tax year 2026/27 · Region: ${opts.region} · Pension: ${opts.pensionPct}% · Student loan: ${opts.studentLoan}`, 40, y);
  y += 30;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 20;

  const row = (label: string, value: string, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(11);
    doc.setTextColor(bold ? 0 : 60);
    doc.text(label, 40, y);
    doc.text(value, W - 40, y, { align: "right" });
    y += 18;
  };

  row("Gross salary", fmt2(result.totalGross));
  row("Pension contribution", `−${fmt2(result.pension)}`);
  row("Taxable gross", fmt2(result.taxableGross));
  row("Personal allowance", fmt2(result.personalAllowance));
  row("Taxable income", fmt2(result.taxableIncome));
  y += 4;
  row("Income Tax", `−${fmt2(result.incomeTax)}`);
  row("National Insurance", `−${fmt2(result.ni)}`);
  if (result.studentLoan > 0) row("Student Loan", `−${fmt2(result.studentLoan)}`);
  y += 10;
  doc.line(40, y, W - 40, y);
  y += 18;
  row("Net take-home (annual)", fmt2(result.net), true);
  row("Net take-home (monthly)", fmt2(result.net / 12), true);
  row("Effective rate", `${result.effectiveRate.toFixed(2)}%`, true);

  y += 30;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by uknetpay.co.uk · For information only · Not financial advice.", 40, y);

  doc.save(`uknetpay-${Math.round(result.totalGross)}.pdf`);
}