export type PdfRow = { label: string; value: number | string; negative?: boolean; bold?: boolean };

/* ASCII-safe currency formatter */
const pdfMoney = (n: number) => {
  const abs = Math.abs(n);
  return `GBP ${abs.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;
};

/**
 * Lazily imports jsPDF on first call — keeps jspdf out of the initial JS bundle
 * so it doesn't block page load. The 605 KB chunk only downloads when the
 * user clicks "Download PDF".
 */
export async function downloadToolPdf(opts: {
  title: string;
  subtitle: string;
  rows: PdfRow[];
  filename: string;
}) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = 595;
  let y = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(opts.title, 40, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  y += 18;
  doc.text(opts.subtitle, 40, y);
  y += 30;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 20;

  for (const row of opts.rows) {
    if (row.label === "---") {
      y += 6;
      doc.line(40, y, W - 40, y);
      y += 14;
      continue;
    }
    doc.setFont("helvetica", row.bold ? "bold" : "normal");
    doc.setFontSize(11);
    doc.setTextColor(row.bold ? 0 : 60);
    doc.text(row.label, 40, y);
    const val =
      typeof row.value === "number"
        ? row.negative
          ? `-${pdfMoney(row.value)}`
          : pdfMoney(row.value)
        : row.value;
    doc.text(val, W - 40, y, { align: "right" });
    y += 18;
  }

  y += 30;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by uknetpay.co.uk | For information only | Not financial advice.",
    40,
    y
  );

  doc.save(opts.filename);
}
